### ISSUE TITLE
用户注册 输入信息检测和提示不起作用

### ISSUE THREAD

**Issue by pei-han** [luoyjx/gaoqi-blog#42]
![image](https://cloud.githubusercontent.com/assets/1300292/16826872/c3d783ce-49b3-11e6-8b0b-6c8b39c367be.png)

![image](https://cloud.githubusercontent.com/assets/1300292/16827030/22b6bca6-49b5-11e6-80f2-8ae402e244eb.png)

**Comment by luoyjx** [comment]
这个好像是那个js缺失了

**Comment by luoyjx** [comment]
重新打包了一下，可以了
