### ISSUE TITLE
外部样式表应该放在header元素里面，外部脚本应该放到body元素最后，以提高页面渲染的速度

### ISSUE THREAD

**Issue by pei-han** [luoyjx/gaoqi-blog#45]
如图：
![image](https://cloud.githubusercontent.com/assets/1300292/16895480/3efd3c72-4baa-11e6-9804-5d31391f9a10.png)
![image](https://cloud.githubusercontent.com/assets/1300292/16895481/4c6fec2e-4baa-11e6-8d37-780acf8c273d.png)

这些css文件和js文件在模板渲染输出到客户端时，直接放在了模板的前面和后面。
这样，在浏览器端渲染是低效的

**Comment by pei-han** [comment]
npm install ejs-mate 下载的是2.0.0版本，并没有block函数。不能使用block带来的便利来解决这个问题。
可以github下载最新的ejs-mate版本来解决

**Comment by luoyjx** [comment]
但是你在模板页中的js依赖一些公共库，但是在它之前还没有加载不会出错？

**Comment by pei-han** [comment]
layout.html这个样板文件里面的js外部文件 放到body元素最后。我有个方案，你先看看。
![image](https://cloud.githubusercontent.com/assets/1300292/16901609/6aee3c9c-4c7b-11e6-931f-ec8e9f917fa4.png)
![image](https://cloud.githubusercontent.com/assets/1300292/16901616/8e23579c-4c7b-11e6-9d2b-b853c1cf246e.png)

**Comment by pei-han** [comment]
@luoyjx  第二个截图是post/edit.html

**Comment by luoyjx** [comment]
如此的话，可以，你那边本地有尝试？

**Comment by pei-han** [comment]
@luoyjx  后面那两张截图就是尝试改了一下发表文章模块的edit.html页面和样板页面layout.html，测试了一下可以实现目的

**Comment by luoyjx** [comment]
已经加上了
