### ISSUE TITLE
文章发布，tag提示时css层级问题

### ISSUE THREAD

**Issue by luoyjx** [luoyjx/gaoqi-blog#54]
![x02jr4y3iy 9 k 0_ a](https://cloud.githubusercontent.com/assets/4217102/18941080/7b7de450-8640-11e6-8149-cf2c02daf136.png)

**Comment by pei-han** [comment]
这个问题，我我的pr解决了。你没有merge

**Comment by luoyjx** [comment]
那你得更新下代码到最新版本了
